### PR TITLE
header done

### PR DESCRIPTION
**Pull request by ViktorZvonar**

### CODE REVIEW

**Review by Raazk10 — APPROVED** [review]

**Comment by sania-farooq** [comment]
hi guys, im struggling a little bit with working with github... please may i get some advice on how to do the pull and commits?

**Comment by Raazk10** [comment]
you have to clone the project first and create new feature branch from main. like 1.click on main in visual studio 2. create new branch from 3. give name of the branch for example. feature/add-contact-us-page and then commit your changes and push. 4. from github project page create pull request. One of us have to review and accept it. The person who create pull request cannot merge it.

**Comment by sania-farooq** [comment]
thanks so much, i will try this

**Comment by ViktorZvonar** [comment]
i left some instructions for you in slack as well. hope it will be helpful

**Pull request merged**
